### PR TITLE
allow int as type for batch_shape

### PR DESCRIPTION
**Pull request by paul-buerkner**
As discussed. @LarsKue feel free to edit as you wish :-)

### CODE REVIEW

**Comment by LarsKue** [comment]
I agree about putting validators into utils. However, the validator function should also actually validate the shape, not just convert ints to tuples.

**Comment by stefanradev93** [comment]
See my recent commit.

**Comment by stefanradev93** [comment]
We also need a function that validates if NaNs, Infs, etc are present in the approximator / simulator outputs. The latter is especially important, as it can help users immediately spot problems.

**Comment by paul-buerkner** [comment]
would it make sense to rename argument from batch_shape to batch_size even if we (for now) keep allowing multi dim batches? we also have batch_size later on on approximator.sample and I fail to see why we sometimes use batch_shape and sometimes batch_size

**Comment by LarsKue** [comment]
The approximator used to support a batch_shape but I had to simplify this a little bit to get it to work cleanly. Ideally I would like to support multi-dimensional batch shapes everywhere, but this can be overly complicated sometimes

**Comment by paul-buerkner** [comment]
Okay, but there would be no issue renaming batch_shape to batch_size, right? We can still support multi dim batch_sizes where we can/want.

**Comment by paul-buerkner** [comment]
Closing this PR as I think it will be implemented instead in #239

**Pull request closed without merging**
