### PR TITLE
Adding a small tutorial how to use SBML models with BayesFlow

### PR DESCRIPTION
**Pull request by arrjon**
#146 updated to the new BayesFlow version :)

### CODE REVIEW

**Comment by paul-buerkner** [comment]
Very cool! I will take a look at it today!

**Comment by paul-buerkner** [comment]
This looks really good! I assume you will add something to the inference phase too?

**Comment by arrjon** [comment]
I did not want to explain things which are explained in other notebooks already, but I could add something on the inference phase or diagnostics if this is helpful :)

**Comment by paul-buerkner** [comment]
Made some minor edits to the notebook and will merge it now. Thank you again for contributing to BayesFlow!

**Pull request merged**
