### PR TITLE
Adding a small tutorial how to use SBML models with BayesFlow

### PR DESCRIPTION
**Pull request by arrjon**
I have included a brief tutorial on how to utilize an SBML model with BayesFlow (the SBML format is very often used in computational systems biology). In the other tutoirals, users need to define and simulate the model manually. However, in this tutorial, we demonstrate the process of loading a model from the BioModels database, utilizing a simulator designed to handle SBML data format, and showcasing the seamless integration with BayesFlow. I hope you find it useful :)

### CODE REVIEW

**Comment by stefanradev93** [comment]
That's fantastic, Jonas! Thanks!

When I try to view the notebook with the GitHub renderer, I get:

Invalid Notebook
'execution_count' is a required property
Using nbformat v5.9.2 and nbconvert v7.16.1

I will try to open the notebook from my dev PC later.

**Comment by arrjon** [comment]
I just rerun the notebook and pushed it again. At least I can view it with the GitHub renderer

**Comment by paul-buerkner** [comment]
Hi @arrjon I am sorry for our inactivity. We have been busy with developing the new bayesflow interface (on the dev branch). Would it be possible for you to port it to the new interface? I am more than happy to review it then and add it to our list of examples. I fully understand of course if you don't have the time of course. Please let me know if you have any questions.

**Comment by arrjon** [comment]
No probelms, I will update the example soon!

**Pull request closed without merging**
