### PR TITLE
Added Documentation to Adapter Transforms 

### PR DESCRIPTION
**Pull request by eodole**
Documentation added to:

- concatonate.py: not sure if the options are all correct... can inference_conditions" be specified as the into string?
- drop.py: this just seems like the opposite of keep, I'm not sure why we have both
- elementwise_transform.py : not sure what this does other than be a parent class

### CODE REVIEW

**Review by paul-buerkner — CHANGES_REQUESTED** [review]
Thank you! please see my minor comments.

**Comment by paul-buerkner** [comment]
Thank you! We have both keep and drop because it may be more efficient to use either of the two depending on the application. Doc for ElementwiseTransform looks good.

**Comment by eodole** [comment]
I changed the documentation in 
- standardization.py: I wasn't sure about the mean/std explaination, I could also remove saying that people should specify their own mean/std because im not really sure what the use case would be
- transform.py 
- one_hot.py

**Comment by paul-buerkner** [comment]
I think this now looks good, thank you! Will merge now. About your standardize question: You are not sure what the use-case would be for the mean and SD inferred from data? Or the use case of a user-specified mean and SD?

**Pull request merged**
